<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistArrayPushXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistArrayPushXHPASTLinterRule.php',
    'ArcanistArrayPushXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistArrayPushXHPASTLinterRuleTestCase.php',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistDuplicateFunctionDeclarationXHPASTLinterRule.php',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase.php',
    'ArcanistDuplicateMethodDeclarationXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistDuplicateMethodDeclarationXHPASTLinterRule.php',
    'ArcanistDuplicateMethodDeclarationXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistDuplicateMethodDeclarationXHPASTLinterRuleTestCase.php',
    'ArcanistDuplicatePropertyDeclarationXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistDuplicatePropertyDeclarationXHPASTLinterRule.php',
    'ArcanistDuplicatePropertyDeclarationXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistDuplicatePropertyDeclarationXHPASTLinterRuleTestCase.php',
    'ArcanistGotoXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistGotoXHPASTLinterRule.php',
    'ArcanistGotoXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistGotoXHPASTLinterRuleTestCase.php',
    'ArcanistNewlineAfterNamespaceXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistNewlineAfterNamespaceXHPASTLinterRule.php',
    'ArcanistNewlineAfterNamespaceXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistNewlineAfterNamespaceXHPASTLinterRuleTestCase.php',
    'ArcanistSwitchCaseSemicolonXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistSwitchCaseSemicolonXHPASTLinterRule.php',
    'ArcanistSwitchCaseSemicolonXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistSwitchCaseSemicolonXHPASTLinterRuleTestCase.php',
    'ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRule.php',
    'ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRuleTestCase.php',
    'FlarcFilesystem' => 'filesystem/FlarcFilesystem.php',
    'FlarcFilesystemTestCase' => 'filesystem/__tests__/FlarcFilesystemTestCase.php',
    'FlarcLibraryTestCase' => '__tests__/FlarcLibraryTestCase.php',
    'FreelancerPhpunitTestEngine' => 'unit/engine/FreelancerPhpunitTestEngine.php',
    'FreelancerPhpunitTestEngineTestCase' => 'unit/engine/__tests__/FreelancerPhpunitTestEngineTestCase.php',
    'PHPUnitCoversXHPASTLinterRule' => 'lint/linter/xhpast/rules/PHPUnitCoversXHPASTLinterRule.php',
    'PHPUnitCoversXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/PHPUnitCoversXHPASTLinterRuleTestCase.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistArrayPushXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistArrayPushXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistDuplicateMethodDeclarationXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistDuplicateMethodDeclarationXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistDuplicatePropertyDeclarationXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistDuplicatePropertyDeclarationXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistGotoXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistGotoXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistNewlineAfterNamespaceXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistNewlineAfterNamespaceXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistSwitchCaseSemicolonXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistSwitchCaseSemicolonXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistSwitchMultipleDefaultStatementsXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'FlarcFilesystem' => 'Phobject',
    'FlarcFilesystemTestCase' => 'PhutilTestCase',
    'FlarcLibraryTestCase' => 'PhutilLibraryTestCase',
    'FreelancerPhpunitTestEngine' => 'ArcanistUnitTestEngine',
    'FreelancerPhpunitTestEngineTestCase' => 'PhutilTestCase',
    'PHPUnitCoversXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'PHPUnitCoversXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
  ),
));
