<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistDuplicateFunctionDeclarationXHPASTLinterRule.php',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase.php',
    'ArcanistGotoXHPASTLinterRule' => 'lint/linter/xhpast/rules/ArcanistGotoXHPASTLinterRule.php',
    'ArcanistGotoXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/ArcanistGotoXHPASTLinterRuleTestCase.php',
    'FlarcFilesystem' => 'filesystem/FlarcFilesystem.php',
    'FlarcFilesystemTestCase' => 'filesystem/__tests__/FlarcFilesystemTestCase.php',
    'FlarcLibraryTestCase' => '__tests__/FlarcLibraryTestCase.php',
    'FreelancerPhpunitTestEngine' => 'unit/engine/FreelancerPhpunitTestEngine.php',
    'FreelancerPhpunitTestEngineTestCase' => 'unit/engine/__tests__/FreelancerPhpunitTestEngineTestCase.php',
    'PHPUnitCoversXHPASTLinterRule' => 'lint/linter/xhpast/rules/PHPUnitCoversXHPASTLinterRule.php',
    'PHPUnitCoversXHPASTLinterRuleTestCase' => 'lint/linter/xhpast/rules/__tests__/PHPUnitCoversXHPASTLinterRuleTestCase.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistDuplicateFunctionDeclarationXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'ArcanistGotoXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'ArcanistGotoXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
    'FlarcFilesystem' => 'Phobject',
    'FlarcFilesystemTestCase' => 'PhutilTestCase',
    'FlarcLibraryTestCase' => 'PhutilLibraryTestCase',
    'FreelancerPhpunitTestEngine' => 'ArcanistUnitTestEngine',
    'FreelancerPhpunitTestEngineTestCase' => 'PhutilTestCase',
    'PHPUnitCoversXHPASTLinterRule' => 'ArcanistXHPASTLinterRule',
    'PHPUnitCoversXHPASTLinterRuleTestCase' => 'ArcanistXHPASTLinterRuleTestCase',
  ),
));
